### ISSUE TITLE
Getting EAPI:Invalid nonce from Kraken

### ISSUE THREAD

**Issue by pjbrinck** [nothingisdead/npm-kraken-api#13]
Using your nice little tool to communicate with Kraken, but getting EAPI:Invalid nonce from Kraken. Tried to console.log the nonce generated, and it increments nicely. Yet still getting error from Kraken, not consistently but rather randomly and often. And when I get it, its when I run two calls in parallel, not waiting for one to complete before the other initiates (not chaining them thru the callback). The nonce increments with 2000 or 3000 (2-3 miliseconds). I have tried using a variety of different key/secret to Kraken, but same result. Any idea what it could be or how to investigate further.

added: Im thinking it may be a race condition on the internet, in which the latter request sometimes passes the former request en route to Kraken. This is solved by always sequencing two dependent calls to Kraken. But if my service becomes busy and receives two independent request each going to Kraken around the same time, Im back to facing the same issue. Any suggestions ?

**Comment by nothingisdead** [comment]
You could try using a microtime package to generate the nonce, e.g. https://www.npmjs.com/package/microtime. That should make those errors significantly less likely. I think I remember that package having an issue with Windows, but I don't see it now. If you don't get to it, I will probably do this when I have some time.

Thanks!

**Comment by Levino** [comment]
Hey @pjbrinck, you cannot do multiple async calls for one key/secret pair to the Kraken API. You cannot rely on the first request being the first received by Kraken. You need to wait for the result of the first call to come back before you should start the next one. Use "async" or promises for that.

On how to scale this one would need a little more info on the kind of requests that you are doing. Maybe you should rely on data that you have locally and get it from time to time in bulk?

**Comment by Levino** [comment]
@nothingisdead This is not at all a problem with the nonce generation and not really an issue with your app, I think.
