### ISSUE TITLE
kraken-api is not working

### ISSUE THREAD

**Issue by Ayms** [nothingisdead/npm-kraken-api#21]
I tried your module with node v0.11.14 since kraken-api is using the binary format which is deprecated now in recent nodejs versions

There must me something wrong with the request module since I always got [Error: Kraken API returned error: General:Internal error]

So I replaced the call to request by a standard https request and this is now working

Not sure what the pb is exactly but at least you should replace the binary format and see what happens with recent nodejs versions, maybe take a look at https://github.com/Ayms/bitcoin-wallets/blob/master/SHA256Compress.js for "stupid" binary manipulations

**Comment by maximkott** [comment]
@Ayms Can you please elaborate on this issue? How did you manage to fix this error? Thanks!

**Comment by Ayms** [comment]
As mentioned above, replacing request by standard https request

As stated above too I think you have to replace the binary format too (using an old nodejs version that supports it unlike latest ones)

**Comment by nothingisdead** [comment]
I never saw this error, but I have replaced the request module with https://www.npmjs.com/package/got. Please open a new issue if it persists.

Thanks!
