### ISSUE TITLE
Timeouts too low

### ISSUE THREAD

**Issue by Amtrix** [nothingisdead/npm-kraken-api#27]
The API is throwing a lot of errors with the current timeout (even though requests get processes by kraken). I have an *extremely* better experience with 60.   It should be expected to deal with huge delays when working with kraken.

**Comment by moonlitknight** [comment]
While increasing the timeout, will reduce the number of timeout failures, it won't eliminate the possibility of timeouts that are actually processed.

**Comment by tvb** [comment]
I facing the same issues:
```
Error in server response: {"code":"ETIMEDOUT","connect":false}
```
I get these very often
