### ISSUE TITLE
After a few API requests i start gettting Error: API:Invalid nonce

### ISSUE THREAD

**Issue by axeldomingues** [nothingisdead/npm-kraken-api#48]
Hi Kraken Team,

After a few API requests i start gettting Error: API:Invalid nonce

I already increased by the nonce window from 7 to 7000 & 15000, i got the same result anyway.

I also start sparsing by calls to the API by random milliseconds, it did not help either... :(

Error: API:Invalid nonce
    at rawRequest (C:\Users\adomingues\Documents\testKraken\node_modules\kraken-api\kraken.js:54:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Any help?

Thanks,
Axel

**Comment by axeldomingues** [comment]
Found the problem! Common JS thing, i was reusing the params object and the client had previously set the a nonce. Thanks anyway.

**Comment by ScottSavarie** [comment]
@axeldomingues I'm hitting the same issue. What are you referring to when you mention reusing the params object? Do you mean the parameters object you can pass into the function to filter your API results? If so what was your workaround? Thanks for any help!

**Comment by axeldomingues** [comment]
yes, the parameters object must be new every call. I hope it helps. Cheers
