### ISSUE TITLE
can the project owner just pass on the torch or someone fork, suggestions for alternatives?

### ISSUE THREAD

**Issue by molecular** [nothingisdead/npm-kraken-api#81]
There are 11 pull requests that all look like they make sense and tons of open issues. It doesn't look like this is maintained any more, but it's reachable through npm...

There are 181 forks of this code. Who knows which one is well-maintained and can be installed through npm.

Anyone have other suggestions on what to use, like maybe https://github.com/jpcx/node-kraken-api ?

**Comment by nothingisdead** [comment]
See #66

**Comment by molecular** [comment]
thx, @nothingisdead
